comment: off
codecov:
  token: 36743525-d093-4119-9e55-39aa2ebe1ae1
ignore:
  - "src/main/java/com/singlestore/jdbc/plugin/authentication/standard/ed25519"  # ignore folders and all its contents
  - "src/main/java/com/singlestore/jdbc/plugin/credential/aws"
  - "src/main/java/com/singlestore/jdbc/plugin/authentication/addon"
